parent_config: https://raw.githubusercontent.com/SPHTech/SPHSwiftlint/master/.swiftlint.yml

line_length:
  warning: 150
  ignores_function_declarations: true
  ignores_comments: true
  ignores_interpolated_strings: true
  ignores_urls: true
type_name:
  max_length: 60
  min_length: 3
cyclomatic_complexity: 20
